export const LOAD_USERS = 'LOAD_USERS_OK'
export const LOAD_TWEETS = 'LOAD_TWEETS_OK'
export const ADD_TWEET = 'ADD_TWEET_OK'
export const ADD_USER = 'ADD_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED'
export const FIND_USER = 'FIND_USER'
